/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface MyButton {
    /**
     * Indicates if the button is disabled
     */
    disabled: boolean;
    /**
     * Variant of the button
     */
    kind: 'default' | 'primary' | 'secondary';
    /**
     * Label text of the button
     */
    label: string;
    /**
     * Size of the button
     */
    size: 's' | 'm' | 'l';
    /**
     * Type attribute of the button
     */
    type: 'button' | 'submit' | 'reset';
  }
}
declare global {
  interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {}
  var HTMLMyButtonElement: {
    prototype: HTMLMyButtonElement;
    new (): HTMLMyButtonElement;
  };
  interface HTMLElementTagNameMap {
    'my-button': HTMLMyButtonElement;
  }
}
declare namespace LocalJSX {
  interface MyButton {
    /**
     * Indicates if the button is disabled
     */
    disabled?: boolean;
    /**
     * Variant of the button
     */
    kind?: 'default' | 'primary' | 'secondary';
    /**
     * Label text of the button
     */
    label?: string;
    /**
     * Size of the button
     */
    size?: 's' | 'm' | 'l';
    /**
     * Type attribute of the button
     */
    type?: 'button' | 'submit' | 'reset';
  }
  interface IntrinsicElements {
    'my-button': MyButton;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'my-button': LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
    }
  }
}
